routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', "HomeController@index")->name('index');
Route::get('contacts', function () {
	
	$id = 2;
  $contacts = \App\Contacts::find($id);

  return view('contacts', compact('contacts'));
});

Route::resource('dishes', 'DishesMenuController');
Route::resource('menu', 'MenuController');
Route::post('/cart', 'CartController@store')->name('cart.store');

Route::post('/cartclear', 'CartController@destroyAll')->name('cart.destroyAll');
Route::post('/cartclearone', 'CartController@destroyOne')->name('cart.destroyOne');
Route::get('/cartindex', 'CartController@index')->name('checkout');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('order', 'OrderController');
});

Auth::routes();

resources/views/contacts.blade.php
@extends('layouts.app')

@section('content')

<script src="{{ asset('js/jquery-1.11.2.min.js') }}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDuihE6DTENsn1dsEMWQ_On-y12PmuRt_M"></script>
        <script>
            function initialize() {
                var mapCanvas = document.getElementById('map-canvas');
                var mapOptions = {
                    center: new google.maps.LatLng({{ $contacts->latitude }}, {{ $contacts->longitude }}),
                    zoom: 6,
                    scrollwheel: false,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                }
                var map = new google.maps.Map(mapCanvas, mapOptions)

                var marker = new google.maps.Marker({
                    position: new google.maps.LatLng({{ $contacts->latitude }}, {{ $contacts->longitude }}),
                    title:" {{ $contacts->name }}"
                });

                // To add the marker to the map, call setMap();
                marker.setMap(map);
            }
            google.maps.event.addDomListener(window, 'load', initialize);
        </script>

<div class="contact">
            <div class="container-fluid color-bg">
                <div class="row dis-table">
                    <div class="hidden-xs col-sm-6 dis-table-cell">
                        <h2 class="section-title">Contact With us</h2>
                    </div>
                    <div class="col-xs-6 col-sm-6 dis-table-cell">
                        <div class="section-content">
                        <p>{{ $contacts->name }}</p>
  						<p>{!! $contacts->working_hours !!}</p>
  						<p>{{ $contacts->info }}</p> 
                        </div>
                    </div>
                </div>
                <div class="social-media">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3">
                            <ul class="center-block">
                                <li><a href="#" class="fb"></a></li>
                                <li><a href="#" class="twit"></a></li>
                                <li><a href="#" class="g-plus"></a></li>
                                <li><a href="#" class="link"></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="container-fluid">
            <div class="row">
                <div id="map-canvas"></div>
            </div>
        </div>



        <section class="contact-form">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
                        <div class="row">
                             <form class="contact-form" method="post" action="contact.php">
                                
                                <div class="col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <input  name="name" type="text" class="form-control" id="name" required="required" placeholder="  Name">
                                    </div>
                                    <div class="form-group">
                                        <input name="email" type="email" class="form-control" id="email" required="required" placeholder="  Email">
                                    </div>
                                    <div class="form-group">
                                        <input name="subject" type="text" class="form-control" id="subject" required="required" placeholder="  Subject">
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6">
                                    <textarea name="message" type="text" class="form-control" id="message" rows="7" required="required" placeholder="  Message"></textarea>
                                </div>

                                <div class="col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3">
                                    <div class="text-center">
                                        <button type="submit" id="submit" name="submit" class="btn btn-send">Send </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	@foreach ($menus as $menu)  
    <div class="row space-bottom-5">
                        
        <h3 class="padding-left-20"><a class="red" href="{{ route('menu.show', $menu->id) }}">{{ $menu->title }}</a></h3>
        @if(auth::check() && auth::user()->is_admin)
        <a class="red padding-left-20" href="{{ route('dishes.create')}}?id={{$menu->id}}">Add a new dish</a>
        <a class="red" href ="{{ route('menu.edit', $menu->id) }}">( Edit )</a>
        @endif
    </div>
    <div class="row">
        @foreach($menu->dishes->take(3) as $index => $dish)
        <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="dish">
                <div class="dish-img">
                    <a href="{{ route('dishes.show', $dish->id)}}"><img class="img img-responsive" src="{{ url($dish->photo) }}"></a>
                </div>
                <div class="dish-info">
                    <h4><a class="title" href="{{ route('dishes.show', $dish->id)}} ">{{ $dish->name }}</a></h4>
                    <p class ="justify"><i>{{ mb_strimwidth($dish->description, 0, 50, '...') }}</i></p>
                    <p>Kaina: {{ $dish->price }} €</p>
                    @if(auth::check() && auth::user()->is_admin)
                    <a class="btn btn-primary" href="{{ route('dishes.edit',$dish->id) }}">Edit</a>
                    @endif
                    <a class="addtocart btn btn-default" href="#" data-dish-id="{{$dish->id}}">ADD to Chart</a>
                </div>
            </div>
        </div>
            
        @endforeach
    </div>
    @endforeach
</div>

@endsection


								