routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', "HomeController@index")->name('index');
Route::get('contacts', function () {
	
	$id = 2;
  $contacts = \App\Contacts::find($id);

  return view('contacts', compact('contacts'));
});

Route::resource('dishes', 'DishesMenuController');
Route::resource('menu', 'MenuController');
Route::post('/cart', 'CartController@store')->name('cart.store');

Route::post('/cartclear', 'CartController@destroyAll')->name('cart.destroyAll');
Route::post('/cartclearone', 'CartController@destroyOne')->name('cart.destroyOne');
Route::get('/cartindex', 'CartController@index')->name('checkout');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('order', 'OrderController');
});

Auth::routes();

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{


    protected $fillable = ["table_id", "number_of_persons", "contact_phone", "reserved_at", "reservation_date",];

     public function user()
    {
        return $this->belongsTo('App\User');
    }


      public function orderItems()
    {
        return $this->hasMany('App\OrderItem');
    }

       public function table()
    {
        return $this->belongsTo('App\Table');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\Order;
use App\Table;
use Carbon\Carbon;

class OrderController extends Controller
{

    public function __construct(){
        $this->middleware('cart.empty')->except('index');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $orders = Auth::user()->orders;
        //where user_id =dabartinis

        return view('orders.orderedIndex', compact('user', 'orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user   = Auth::user();
        $tables = Table::all();
        $tables = $tables->pluck('nameWithCapacity', 'id');
        return view('orders.orderCreate', compact('user', 'tables'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        $this->validate($request, [
        'table_id' => 'required|exists:tables,id|integer',
        'contact_phone' => 'required|min:8|max:12',
        'number_of_persons' => 'required|min:1|max:100|integer',
        'reserved_at' => 'required|date_format:Y-m-d H:i'
    ]);


        $capacity = Table::find($request->table_id)->number_of_persons;
        $number_of_persons=$request->number_of_persons;
        if($capacity < $number_of_persons){
            return redirect()
            ->back()
            ->withErrors('Zmones netelpa')
            ->withInput();
        }
        $before = new Carbon($request->reserved_at);
        $before = $before->subHours(1);

        $after = new Carbon($request->reserved_at);

        $after = $after->addHours(1);

        

        $orders = Order::whereBetween('reserved_at' , [$before, $after])->where('table_id', $request->table_id
            )->get();

        if(count($orders)){
            return back()
            ->withErrors('Table is reserved')
            ->withInput();
        }

        $data = $request->all();

        $user = Auth::user();

        $order = $user->orders()->create($data);

        $cartItems=session()->get('cart.items');

        foreach ($cartItems as $item) {

            $item['dish_id'] = $item['id'];
            $item['title'] = $item['name'];
            $order->orderItems()->create($item);
        }

        $request->session()->forget('cart.items');
        $request->session()->forget('cart.total_items');
        $request->session()->forget('cart.total_amount');


        //nebaigta

        return redirect()->route('order.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::find($id);

        return view('orders.success', compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/orders/checkout.blade.php
@extends('layouts.app')
@section('content')

	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-10 col-md-offset-1">
				<table class="table table-hover">
				@if(Session::get('cart.total_items') > 0)
					<thead>
						<tr>
							<th>Product</th>
							<th>Quantity</th>
							<th class="text-center">Price</th>
							<th class="text-center">Total</th>
							<th> </th>
						</tr>
					</thead>
					<tbody>
						@foreach($items as $item)
						
						<tr>
							<td class="col-sm-8 col-md-6">
							<div class="media">
								<a class="thumbnail pull-left" href="#"> <img class="media-object" src="{{ url($item['photo']) }}" style="width: 72px; height: 72px;"> </a>
								<div class="media-body">
									<h4 class="media-heading"><a href="#">{{ $item['name'] }}</a></h4>
									<h5 class="media-heading"> by <a href="#">{{ $item['description'] }}</a></h5>
									<span>Status: </span><span class="text-success"><strong>In Stock</strong></span>
								</div>
							</div></td>
							<td class="col-sm-1 col-md-1" style="text-align: center">
							<input type="number" class="form-control" id="" value="{{ $item['cart_count'] }}">
							</td>
							<td class="col-sm-1 col-md-1 text-center"><strong>{{ $item['price'] }}€</strong></td>
							<td class="col-sm-1 col-md-1 text-center"><strong>{{ number_format($item['price'] * $item['cart_count'], 2, '.', '') }} €</strong></td>
							<td class="col-sm-1 col-md-1">
							<button type="button" class="btn btn-danger js-remove" data-item="{{ $item['id']}}">
								<span class="fa fa-remove "></span> Remove
							</button></td>
						</tr>
						@endforeach

					</tbody>
					<tfoot>
						<tr>
							<td>   </td>
							<td>   </td>
							<td>   </td>
							<td><h3>Total</h3></td>
							<td class="text-right total-checkout"><h3>{{ Session::get('cart.total_amount') }} €</h3></td>
						</tr>
						<tr>
							<td>   </td>
							<td>   </td>
							<td>   </td>
							<td>
							<a href="{{route('index')}}" class="btn btn-default">
								<span class="fa fa-shopping-cart"></span> Continue Shopping
							</a></td>
							<td>
							<a class="btn btn-success" href="{{ route('order.create') }}">
								Checkout <span class="fa fa-play"></span>
							</a></td>
						</tr>
					</tfoot>
					@else
					<tr>
						<td>
							<h4>Shopping Cart</h4>
							<p>Your shopping cart is empty</p>
						</td>
					</tr>
					<tr>
						<td>
							<a href="{{ route('index') }}" class="btn btn-default"><span class="fa fa-shopping-cart"></span> Continue Shopping</a>
						</td>
					</tr>
					@endif
				</table>
			</div>
		</div>
	</div>

@endsection

resources/views/orders/orderCreate.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	@if (count($errors) > 0)
	<div class="alert alert-danger">
		<ul>
			@foreach ($errors->all() as $error)
			<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
	@endif

	<div class="row">

		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					Reservarion Details
				</h3>
			</div>
			<div class="panel-body">
				<form role="form" method="POST" action="{{ route('order.store') }}">

					<div class="row">

						{{--{{ Form::open(['url' => route('order.store')]) }}--}}

						{{ csrf_field() }}
						<div class="row">
							<div class="form-group">
								<label for="table_id" class="col-md-2 col-md-offset-2 control-label">Table</label>
								<div class="col-md-8">
			                        <select name="table_id" id="table_id">
			                         @foreach($tables as $id => $name)
			                         	<option value="{{$id}}" {{ old('table_id')==$id?'selected':'' }}>{{$name}}</option>
			                         @endforeach
			                     	</select>
								</div>
							</div>
						</div>

						<div class="row">
							<div class="form-group">
								<label for="number_of_persons" class="col-md-2 col-md-offset-2 control-label">Number Of Persons</label>
								<div class="col-md-8">
									<input type="number" name="number_of_persons" value="{{old('number_of_persons', '2') }}" min="1">
								</div>
							</div>
						</div>

						<div class="row">
							<div class="form-group">
								<label for="contact_phone" class="col-md-2 col-md-offset-2 control-label">Phone</label>
								<div class="col-md-8">
									{{--            {{ Form::text('contact_phone', '+370') }}--}}

									<input type="text" name="contact_phone" value="{{old('contact_phone' , '+370')}}">
								</div>
							</div>
						</div>

						<div class="row">
							<div class="form-group">
								<label for="reserved_at" class="col-md-2 col-md-offset-2 control-label">Reservation date and time</label>
								<div class="col-md-8">
									<input type="text" name="reserved_at" value="{{old('reserved_at')}}">	
									<p class="help-block">2016-12-24 16:00</p>
								</div>
							</div>
						</div>


						<div class="row">
							<div class="form-group">
								<div class="col-md-6 col-md-offset-2">
									<button class="btn btn-success" type="submit" name="submit">Submit</button>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/orders/orderedIndex.blade.php
@extends('layouts.app')
@section('content')


<div class="container">
    <div class="row">
		
		{{dd([$user,$orders])}}

	</div>
</div>

@endsection

resources/views/orders/success.blade.php
@extends('layouts.app')
@section('content')


<div class="container">
    <div class="row">
		<h1>Uzsakymas sekmingai patvirtintas</h1>
	</div>
</div>

@endsection